### ISSUE TITLE
Latest available version from NodeBB Plugins ACP outdated

### ISSUE THREAD

**Issue by ylothar** [NodeBB/nodebb-plugin-glossary#8]
Hi,

in NodeBB ACP - NodeBB version v1.18.6 - the latest available version is 0.0.9.

**Comment by barisusakli** [comment]
I see Latest 0.0.13 now, maybe nbbpm update took a while

**Comment by ylothar** [comment]
I still continue to see 0.0.9 as the latest version available

**Comment by barisusakli** [comment]
What do you see when you go to https://packages.nodebb.org/api/v1/suggest?package=nodebb-plugin-glossary&version=1.18.6

**Comment by ylothar** [comment]
![Schermata da 2022-01-05 19-39-35](https://user-images.githubusercontent.com/682247/148270850-a11e75c9-c85a-4c68-9879-5f3dc4fc1f91.png)
![Schermata da 2022-01-05 19-40-59](https://user-images.githubusercontent.com/682247/148271051-6aea159e-5550-4c25-af14-4e6a02c0f789.png)
![Schermata da 2022-01-05 19-41-50](https://user-images.githubusercontent.com/682247/148271157-ea06c05f-c19a-45e5-882a-d1073c4b00cd.png)

**Comment by barisusakli** [comment]
Can you check your package.json to see if nodebb-plugin-glossary is there? What is the value set to?

**Comment by ylothar** [comment]
[...]
    "nodebb-plugin-2factor": "^2.9.7",
    "nodebb-plugin-composer-default": "7.0.14",
    "nodebb-plugin-custom-pages": "^1.3.1",
    "nodebb-plugin-customize": "^2.0.4",
    "nodebb-plugin-dbsearch": "5.1.0",
    "nodebb-plugin-emoji": "^3.5.4",
    "nodebb-plugin-emoji-android": "2.0.5",
    "nodebb-plugin-emoji-fontawesome": "^2.0.5",
    "nodebb-plugin-extended-markdown": "^1.5.0",
    **"nodebb-plugin-glossary": "0.0.9",**
    "nodebb-plugin-google-analytics": "^0.6.1",
    "nodebb-plugin-markdown": "8.14.4",
    "nodebb-plugin-mentions": "3.0.2",
    "nodebb-plugin-question-and-answer": "^0.12.10",
    "nodebb-plugin-recent-cards": "^2.0.19",
    "nodebb-plugin-reputation-rules": "^1.2.3",
    "nodebb-plugin-soundpack-default": "^2.0.0",
    "nodebb-plugin-spam-be-gone": "0.7.11",
    "nodebb-plugin-tenor-gif": "^1.2.8",
    "nodebb-plugin-youtube-embed": "^0.6.9",
[...]

**Comment by barisusakli** [comment]
Can you try changing it to `"^0.0.9"` in package.json and then restart nodebb? See if that shows the latest 0.0.13 in the ACP.

**Comment by ylothar** [comment]
It worked :+1: 
Thank you!!!
